/*
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS covers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS status;
*/

CREATE TABLE IF NOT EXISTS covers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS books (
    id BIGSERIAL PRIMARY KEY,
	isbn VARCHAR(50) UNIQUE NOT NULL,
	author VARCHAR(100) NOT NULL,
	title VARCHAR(100) NOT NULL,
	price DECIMAL(8,2) DEFAULT 0.0 NOT NULL,
	cover_id BIGINT REFERENCES covers,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	role_id BIGINT REFERENCES roles,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS status (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users,
    totalCost DECIMAL(8,2) DEFAULT 0.0 NOT NULL,
    timestamp DATE NOT NULL,
    status_id BIGINT REFERENCES status,
    deleted BOOLEAN DEFAULT false NOT NULL
    );

CREATE TABLE IF NOT EXISTS order_items (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT REFERENCES orders,
    book_id BIGINT REFERENCES books,
    quantity DECIMAL(2) NOT NULL,
    price DECIMAL(8,2) DEFAULT 0.0 NOT NULL,
    deleted BOOLEAN DEFAULT false NOT NULL
    );
